### ISSUE TITLE
Eliminate dependency on yii-core

### ISSUE THREAD

**Issue by samdark** [yiisoft/cache#12]
yii-core should not be required to use cache.

https://github.com/yiisoft/cache/blob/master/composer.json#L76

**Comment by viktorprogger** [comment]
I'll take this ^_^

**Comment by razonyang** [comment]
FileCache is depends on yii-core's FileHelper, we may need make FileHelper separate from yii-core first.

**Comment by machour** [comment]
@razonyang it seems to depend only on it to create folders. It should be sufficient to use `mkdir()` here.

**Comment by samdark** [comment]
Using mkdir or copy-pasting from FileHelper would do for now.
