### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by samdark** [yiisoft/cache#17]

**Comment by alexkart** [comment]
Trying to add tests for dependencies. 
@samdark could you please explain what does this method `getTimestamps` do https://github.com/yiisoft/cache/blob/master/src/Dependency/TagDependency.php#L105. When does it return something other than `['tag' => null]`?

**Comment by samdark** [comment]
`getTimestamps()` is getting multiple keys from cache. Each key corresponds to dependency tag. It returns something other than `null` if `getDependecyData()` was called at least once.

`$timestamp === false` should be replaced with `$timestamp === null`. False was a value for "no cache" in 2.0.

**Comment by alexkart** [comment]
Thanks. Maybe `getTimestamps()` should be renamed? To `getStoredTags()` or something else more meaningful.

**Comment by samdark** [comment]
getTagTimestamps?

**Comment by samdark** [comment]
94% is good enough but if you want 100%, feel free to do so.
