### ISSUE TITLE
Consider removing add() and addMultiple()

### ISSUE THREAD

**Issue by samdark** [yiisoft/cache#20]
`add()` and `addMultiple()` work like `set()` and `setMultiple()` except they store cache only if there is no existing value.

Personally, I've never used it. Need opinions about removing these.

**Comment by tunecino** [comment]
I've never used them either but maybe some random library that requires providing a PSR-16 adapter (like [does florianv/swap](https://github.com/florianv/swap/blob/master/doc/readme.md#cache)) would expect them?

**Comment by samdark** [comment]
No, these are not part of PSR-16. These are added on top of it.

**Comment by samdark** [comment]
https://forum.yiiframework.com/t/cache-is-nearly-final/126716

**Comment by tunecino** [comment]
Oh! Then it is your call. I've personally never seen or heard of a developper complaining about a bonus feature :)

**Comment by samdark** [comment]
> I've never seen or heard about a developper complaining about a bonus feature

Yes, it's mainly maintainers complaining internally :)
