### ISSUE TITLE
Consider moving storage backends into separate repositories

### ISSUE THREAD

**Issue by samdark** [yiisoft/cache#22]
The main point is to achieve proper extension dependencies resolving via Composer.

**Comment by samdark** [comment]
- https://github.com/yiisoft/cache-wincache
- https://github.com/yiisoft/cache-file
- https://github.com/yiisoft/cache-memcached
- https://github.com/yiisoft/cache-apcu/

**Comment by alexkart** [comment]
What about `ArrayCache`?

**Comment by samdark** [comment]
Let's start with others first.

**Comment by alexkart** [comment]
- [ ] https://github.com/yiisoft/cache-wincache
- [ ] https://github.com/yiisoft/cache-file
- [ ] https://github.com/yiisoft/cache-memcached
- [x] https://github.com/yiisoft/cache-apcu/

**Comment by alexkart** [comment]
So, do we need to extract ArrayCache?

**Comment by samdark** [comment]
I think not. There are no significant benefits.

Thank you for handling it.

**Comment by samdark** [comment]
Oh, I forgot that this repository should have some files deleted and travis config cleaned up.
