### ISSUE TITLE
Unreached code

### ISSUE THREAD

**Issue by alexkart** [yiisoft/cache#28]
I think the code inside `if ($this->persistentId !== null) {}` in `\Yiisoft\Cache\Memcached::addServers` can never be executed https://github.com/yiisoft/cache/blob/master/src/Memcached.php#L88.
`addServers()` method is called only from constructor and `$this->persistentId` is always `null` in this case.

The same is for the following blocks https://github.com/yiisoft/cache/blob/master/src/Memcached.php#L114
https://github.com/yiisoft/cache/blob/master/src/Memcached.php#L118
`getMemcached()` is called from the constructor and then `$this->cache` is never `null`.

**Comment by rob006** [comment]
This is probably leftover after removing `init()` method and moving related code to constructor. There were already similar bugs found in the past and I would expect much more of them in other places too.

**Comment by samdark** [comment]
@rob006 is correct. Either these checks could be removed or there are missing arguments for constructor.

**Comment by samdark** [comment]
@alexkart was this one covered in PR?

**Comment by alexkart** [comment]
Yes
