### ISSUE TITLE
Library design

### ISSUE THREAD

**Issue by alexkart** [yiisoft/cache#29]
I was looking into this library, trying to work on some issues, and while working with it I noticed that the design of the library doesn’t feel right.
The first thing that bothers me is SimpleCache class, and that it adds additional functionality from the beginning (keys and values normalization, key prefixes, etc., what if you don’t need normalization or you want to handle it yourself) and those methods setValue, getValue etc. that each backend needs to implement instead of implementing interface methods, this is confusing. I think that different backend classes should just implement PSR interface as minimal as possible without any additional functionality and all additional things can be added to decorator (one or several) like Cache class that currently extends functionality.
It will have several significant benefits:
1) When you are implementing new cache backend, you know exactly what to implement from the PSR interface
2) The functionality of the new cache backend will be as minimal as it’s required by the interface especially if you don’t need any extra functionality, the library will be more general-purpose and you will have the ability to use it with or without extra functionality 
3) All extra functionality will be added via decorators (one common decorator or several more specific ones)

@samdark, so, what do you think of rewriting of the library a bit to this architecture? Is there any reason why we can’t do this or you don’t see any sense doing this? What if I try to implement it and we’ll see if it’s better than the current one?

**Comment by rob006** [comment]
>  2\. The functionality of the new cache backend will be as minimal as it’s required by the interface especially if you don’t need any extra functionality, the library will be more general-purpose and you will have the ability to use it with or without extra functionality

Additional functionality seems to be the whole point of this library. If you want to pure PSR interface implementation, there are existing packages for that.

**Comment by alexkart** [comment]
@rob006, all additional functionality that it provides currently will be saved, I suggest to redesign it a bit, so the internal structure will be simpler and more intuitive.
The only difference in usage will be:
```
$cache = new Memcached(); // pure PSR interface implementation
$cache = new Cache(new Memcached()); // cache with all additional functionality
```

> If you want to pure PSR interface implementation, there are existing packages for that
If there is a good package with pure PSR interface implementations for all backends that are used in this library we could use it and write only additional functionality here, but I don't know what's better, pure PSR implementation is quite simple to maintain it ourselves. And the fact that we will have the ability to swap the PSR implementation classes supports my suggestion of redesign, the library will be more flexible and easier to maintain.

**Comment by rob006** [comment]
>  The only difference in usage will be:

AFAIK it already works in this way: `Yiisoft\Cache\Cache` is a decorator for PSR implementations (handler).

I'm not sure how introducing another layer will simplify anything. `SimpleCache` actually simplifies implementation (things like key normalization or serialization is a must for many backends). AFAIK `SimpleCache` is not a requirement, if you don't need any of its features you can create new class without extending `SimpleCache`.

**Comment by alexkart** [comment]
I’m saying not about adding a layer but removing an extra layer.
Now it’s designed this way: SimpleCache provides some additional functionality and adds abstract methods, then different backend classes provides implementation for those abstract methods, and then Cache decorator provides more additional functionality, so it’s three layers.
What I suggest is backend specific classes implement PSR interface without any extra functionality and then all additional functionality is provided by the Cache decorator, that’s two layers and I think it’s better design.

**Comment by rob006** [comment]
@alexkart `SimpleCache` provides code that should be shared between different backends. The best example is key normalization - most of backends has length limit or does not allow some chars as key. If you remove `SimpleCache`, you need either repeat normalization part in each backend, or create really bad PSR implementation which will break if you provide too long key (so this implementation is quite useless without decorator).

And it is still unclear to me why do you think that implementing cache backend from scratch will be simpler than using `SimpleCache` as a base. `SimpleCache` requires to implement only 5 methods and it already handles some basic stuff like serialization or normalization.

**Comment by alexkart** [comment]
Mainly I think that what is wrong with SimpleCache is that it transforms PSR interface into new very simillar interface and it's a bit weird for me.
I don't say that what I suggest will have a huge difference I just think that the structure of the library will be at least simpler and more readable.

**Comment by rob006** [comment]
> that backend classes need to implement and it's a bit weird for me

There is no such requirement. This library does not rely on `SimpleCache` as a type, this is only a base to keep code more DRY and consistent.

**Comment by samdark** [comment]
## Dropping SimpleCache or moving implementation to individual PSR implementations

If we'll drop `SimpleCache` we'll have to implement the following in each PSR implementation for cache backends:

1. key prefixing
2. default TTL
3. custom serialization support
4. key normalization
5. polyfills in case backend does not support batch operations

The code for points above isn't 100% straightforward so providing it out of the box pre-implemented and unit-tested is simpler than doing it from scratch all the time. So removing this code altogether or moving it to each individual PSR implementation we have is a bad idea.

**Decision**:  We should keep providing above feature points for cache backend implementers.

## Moving implementation into decorator

As an option, all these could be moved to PSR-compatible decorator. We then should somehow to avoid repetitive key normalization but that's doable.

There are multiple issues with it though. First, configuration syntax would get more complicated:

```php
$psrImplementation = new MyPSRCacheBackend();
$driverExtrasDecorator = new DriverExtrasDecorator($psrImplementation); // extra step
$cache = new Cache($driverExtrasDecorator);
```

In case of separation of key prefixing, customizable serialization etc. it could be even more bloated:

```php
$psrImplementation = new MyPSRCacheBackend();

$decoratedPSRCache = new DefaultTTLDecorator(new CustomSeializationDecorator(new KeyPrefixDecorator($psrImplementation)));

$cache = new Cache($decoratedPSRCache);
```

That is, of course, very customizable. Decorators could be combined in any variant needed.

**Comment by alexkart** [comment]
It can be done in such a way that from the usage point of view there will be no extra steps.
Here is what it will look like:
```php
$psrCache = new Memcached(); // cache instance that implements PSR interface without any extra functionality
$cache = new Cache(new Memcached()); // cache instance with all additional functionality (key prefixes, normalization, serialization, dependencies, additional methods etc.)

// the features will be configurable

$cache->enableKeyNormalization(); // enabled by default
$cache->disableKeyNormalization();

$cache->setKeyPrefix('prefix'); // no prefix by default

$cache->setSerializer(new JsonSerializer()); // PhpSerializer() by default
```

In fact, I've already implemented almost all of this to see how it will look like and I can say for sure it looks better for me. While I was working on this I also fixed some issues that I've found, made some refactoring, added lots of tests for uncovered cases.
I've rewritten two backends `ArrayCache` and `Memcached` to the minimal PSR implementation, removed `SimpleCache` class and moved all additional functionality to the `Cache` decorator.
So, I think I'll create a PR tomorrow or in a few days so that you can look at the code and make a decision.

**Comment by samdark** [comment]
I guess that won't work well but, of course, I could be wrong.

It is typical for third party PSR implementations to have built-in key normalization, default TTL etc. It varies a lot from implementation to implementation so turning everything on by default will not work for non-Yii implementations while turning everything off will make configuration even worse than using multiple decorators for Yii-implementations.

Anyway, if it's done, please send a pull request and we'll check it.

**Comment by samdark** [comment]
Another issue with having it in the Cache is that you'll have to type-hint against Yii's cache interface instead of PSR one even if you don't use any extra functionality.

**Comment by alexkart** [comment]
> Another issue with having it in the Cache is that you'll have to type-hint against Yii's cache interface instead of PSR one even if you don't use any extra functionality.

Why? If you type-hint PSR cache, of course, you can't rely on methods for configuration (like `setKeyPrefix`, `setSerializer`) but you will be using the default configuration (like you use features that are currently in `SimpleCache` class). If serialization and normalization are enabled by default they will be used.

```php
class Test
{
    public function providesCache()
    {
        $cache = new Cache(new Memcached());
        $this->usesPsrCache($cache);
    }

    public function usesPsrCache(\Psr\SimpleCache\CacheInterface $cache)
    {
        $cache->set('test', 1);
        $cache->get('test');
    }
}
```

**Comment by samdark** [comment]
Right. You are correct on this one. Our Cache interface extends from PSR one so could be type-hinted as PSR.

**Comment by alexkart** [comment]
> So the only possible issue left is configuration.
What do you mean by this? Currently, you also can't configure it in any way because PSR interface doesn't provide such interface you are using what is passed to you and preconfigured before it gets to a type-hinted method.
So, there is no difference between the current implementation in this one.

**Comment by samdark** [comment]
Meant this:

> It is typical for third party PSR implementations to have built-in key normalization, default TTL etc. It varies a lot from implementation to implementation so turning everything on by default will not work for non-Yii implementations while turning everything off will make configuration even worse than using multiple decorators for Yii-implementations.

i.e. defaults won't work and configuration is becoming very explicit.

**Comment by alexkart** [comment]
I don't get it we can set any defaults we need with new design, to match exactly current implementation or whatever we decide.

**Comment by samdark** [comment]
With your code we can set defaults for whole Cache i.e. for **all** implementations at once. With SimpleCache we can set defaults for Yii implementations only.

**Comment by alexkart** [comment]
What is Yii implementation?

**Comment by alexkart** [comment]
What is Yii implementation?
Do you mean the following in current implementation?
```php
$nonYiiCache = new Memcached();
$yiiCache = new Cache(new Memcached());
```
And you say that they should have different defaults?
OK then, let's create `YiiCache` decorator which extends `Cache` and will have different defaults if we really need this, no big deal.
We will have:
```php
$psrCache = new Memcached();
$nonYiiCache = new Cache(new Memcached());
$yiiCache = new YiiCache(new Memcached());
```
You can choose different defaults or configure everything you need. Quite flexible.

**Comment by samdark** [comment]
Yii implementation is https://github.com/yiisoft/cache/blob/master/src/ApcuCache.php. Non-Yii implementation is https://github.com/kodus/file-cache/blob/master/src/FileCache.php

**Comment by samdark** [comment]
Introducing extra decorator is complicating things. I'd prefer having only a single one.

**Comment by alexkart** [comment]
I see your point, you mean if you want to use `Cache` decorator from this library with non-yii psr implementation. But why would you want to do this? I think it's a bit weird. If you need caching you get one package that satisfies your needs not several of them, I mean it's possible but yes, in this case, you may need to do more configuration then usual. If this library provides whole thing - psr implementations (either it's own or as a external dependency which fits well) and a decorator for them there is no need to adjust decorator for different implementations.
I'm sure that with the current design you can find an external psr implementation that won't fit the `Cache` decorator perfectly without much configuration.

**Comment by samdark** [comment]
> But why would you want to do this?

Exotic cache backend that you don't want to implement yourself.

> I'm sure that with the current design you can also find an external psr implementation that won't fit the Cache decorator perfectly without much configuration.

With the current design defaults are on PSR-16 implementation level so Yii implementations defaults (SimpleCache) do not conflict with whatever is default in external implementation. If you want to "just take a PSR-16 library and use it with Yii" you can do it. You don't have to read its code to find out if it has its own default TTL implementation and configure Yii to turn off its own implementation in this case.

**Comment by alexkart** [comment]
OK, I've created PR. Let me know what you think.
