### ISSUE TITLE
No exception thrown for invalid key characters in storage backends

### ISSUE THREAD

**Issue by mikehaertl** [yiisoft/cache#48]
According to PSR-16 some characters must not be used as keys:

> The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: `{}()/\@:`

`Psr\SimpleCache\CacheInterface` requires an exception to be thrown for invalid keys:

```
     * @throws \Psr\SimpleCache\InvalidArgumentException
     *   MUST be thrown if the $key string is not a legal value.
     */
    public function get($key, $default = null);
```

So as I understand the spec any key containing one of the above characters MUST also be considered invalid and lead to an exception.

This affects all other cache backends (apc, ...)

**Comment by samdark** [comment]
Fixed by adding check to all the concrete implementations.

**Comment by mikehaertl** [comment]
The fix should also be added to `ArrayCache` and `NullCache`. It may be overkill but adding a `Key` value class or a `KeyValidator` to this base class would avoid code repetition.
