### ISSUE TITLE
Reusable property for TagDependency

### ISSUE THREAD

**Issue by ZhandosKz** [yiisoft/cache#5]
### What steps will reproduce the problem?
Many data caching with common TagDependency dependency with **reusable** option that is on.
### What is the expected result?
Decrease Cache::multiGet calls from [isChanged](https://github.com/yiisoft/yii2/blob/master/framework/caching/TagDependency.php#L63) . Reusable property do not use in this method, but in parent class, in the same method **reusable** [used](https://github.com/yiisoft/yii2/blob/master/framework/caching/Dependency.php#L79).
### What do you get instead?

When **reusable** options is on, caching timestamp data of the TagDependency in the static property.

**Comment by samdark** [comment]
There's no such option anymore.

**Comment by samdark** [comment]
No, there is :)

**Comment by samdark** [comment]
It makes sense that tag dependency is not reusable since it needs to get fresh info about tags each time.

**Comment by ZhandosKz** [comment]
@samdark is it impossible to fix?

**Comment by samdark** [comment]
It's possible but using closures with modern PHP is far more convenient so I see no reason to keep ExpressionDependency.

**Comment by samdark** [comment]
Yes, it is not possible since if you'll cache timestamp data then tagged cache won't be invalidated:

```php
$dependency = new TagDependency('item_42');
        $dependency->markAsReusable();

        $cache = $this->getCache();
        $cache->set('item_42_price', 13, null, $dependency);
        $cache->set('item_42_total', 26, null, $dependency);

        $this->assertSame(13, $cache->get('item_42_price'));
        $this->assertSame(26, $cache->get('item_42_total'));

        TagDependency::invalidate($cache, 'item_42');

        // keys are invalidated but are still there
        $this->assertTrue($cache->has('item_42_price'));
        $this->assertTrue($cache->has('item_42_total'));

        $this->assertNull($cache->get('item_42_price')); // <--- will fail
        $this->assertNull($cache->get('item_42_total')); // <--- will fail
```
