### ISSUE TITLE
The get() method should be string, with compatible psr/SimpleCache/CacheInterface::get().

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/cache#52]
The `get()` method must be compatible with `psr/SimpleCache/CacheInterface::get()`

```php
interface CacheInterface
{
    /**
     * Fetches a value from the cache.
     *
     * @param string $key     The unique key of this item in the cache.
     * @param mixed  $default Default value to return if the key does not exist.
     *
     * @return mixed The value of the item from the cache, or $default in case of cache miss.
     *
     * @throws \Psr\SimpleCache\InvalidArgumentException
     *   MUST be thrown if the $key string is not a legal value.
     */
    public function get($key, $default = null);
}
```

**Comment by samdark** [comment]
That's currently a feature of our own Cache wrapper: https://github.com/yiisoft/cache/blob/master/src/CacheInterface.php#L42. Either we should not inherit the interface from PSR cache or make key always a string.

**Comment by samdark** [comment]
It's not particularly useful feature to accept non-string keys. It's saving one-two lines of code at max and I don't see any good use-cases for these.
