### ISSUE TITLE
Prefix restrictions.

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/cache#62]
https://github.com/yiisoft/cache/blob/81977edc24e2a840694a70a6eb331070364d5a64/src/Cache.php#L299-L305

Why impose such restrictions on the prefix when the `is_scalar` constraint is used for the key?

**Comment by samdark** [comment]
See https://www.php-fig.org/psr/psr-16/:

> Key - A string of at least one character that uniquely identifies a cached item. Implementing libraries MUST support keys consisting of the characters A-Z, a-z, 0-9, _, and . in any order in UTF-8 encoding and a length of up to 64 characters. Implementing libraries MAY support additional characters and encodings or longer lengths, but MUST support at least that minimum. Libraries are responsible for their own escaping of key strings as appropriate, but MUST be able to return the original unmodified key string. The following characters are reserved for future extensions and MUST NOT be supported by implementing libraries: {}()/\@:

**Comment by samdark** [comment]
What do you propose?

**Comment by mj4444ru** [comment]
I propose to refuse any checks. This class is not an implementation of caching mechanisms, for this reason it should not impose any restrictions on keys. The prefix can also be an empty string.

The class that implements the cache should be responsible for checking the key. For example:
https://github.com/yiisoft/cache/blob/81977edc24e2a840694a70a6eb331070364d5a64/src/ArrayCache.php#L174-L179

**Comment by samdark** [comment]
Yes, makes sense.
