### ISSUE TITLE
Different stores for cache values and tags.

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/cache#78]
The store for tags in a complex project can be different from the store for the cache itself.
It is necessary to give the opportunity to set the store for tags:
```php
$cache->getOrSet('item_42_price', $callable, null, new TagDependency('item_42', $tagCache));
```

The [Symfony](https://symfony.ru/doc/current/cache.html) cache allows you to set up the tag store via configuration. It would be convenient if we could specify the tag store in the settings of the cache itself.

**Comment by samdark** [comment]
Discussed it internally. That seems to be very rarely needed feature. It can be added later if needed without changing public API in a backwards compatibility breaking manner if it will be requested more.
