### ISSUE TITLE
ExpressionDependency does not work

### ISSUE THREAD

**Issue by seakk** [yiisoft/cache#9]
```php
$updated_at = rand(1, 10);
        echo $updated_at . PHP_EOL;
        $dependency = new \yii\caching\ExpressionDependency(
            [
                //'expression' => 'date("Y-m-d H:i:s")', // normal work
                'expression' => '$this->params', // use 'params' not work
                'params' => ['updated_at' => $updated_at]
            ]
        );
        $cacheKey = 'goods_view';
        $date = Yii::$app->cache->getOrSet($cacheKey, function () {

            return [rand(20, 100)];
        }, 3600, $dependency);

        print_r($date)  ;
        exit();
```

**Also, when changing the expression, you must use './yii cache/flush-all' to clear the cache to take effect.**

How to use both expression and params parameters correctly ？

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      |  5.5
| Operating system | mac os

**Comment by samdark** [comment]
Going to replace it with CallbackDependency since I see no pros in using `eval()` and stings for the case.

**Comment by samdark** [comment]
https://github.com/yiisoft/cache/commit/9742ac91d61322bc5f3d9fecaa6e286460c6a5eb
