### ISSUE TITLE
ArrayCache data loss between several instances

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/cache#95]
### What steps will reproduce the problem?
`
use Yiisoft\Cache\ArrayCache;

$cache1 = new ArrayCache();
$cache2 = new ArrayCache();

$cache1->set('test', 'sddsbsdbdsbds');

var_dump($cache1->has('test')); //True
var_dump($cache2->has('test')); //False
`

So maybe **private array $cache** must be **static**? Otherwise ArrayCache work differently compared with FIleCache, Memcached, APCu etc

**Comment by terabytesoftw** [comment]
That is the expected behavior, `ArrayCache::class` does not implement psr/LoggerInterface::class, therefore it is correct that they do not share data.

**Comment by Gerych1984** [comment]
> That is the expected behavior, `ArrayCache::class` does not implement `psr/LoggerInterface::class` as dependency on constructor, they are two different caches.

Thanks for explanation
